name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    - name: Install musl-tools
      run: sudo apt-get update && sudo apt-get install musl-tools

    - name: Install OpenSSL
      run: |
        wget https://www.openssl.org/source/openssl-1.1.1k.tar.gz
        tar -xzvf openssl-1.1.1k.tar.gz
        cd openssl-1.1.1k
        ./config no-shared --prefix=/usr/local/musl
        make -j$(nproc) && sudo make install

    - name: Build Release with musl and vendored OpenSSL
      env:
        OPENSSL_STATIC: 1
        OPENSSL_DIR: /usr/local/musl
        PKG_CONFIG_ALLOW_CROSS: 1
      run: cargo build --release --target x86_64-unknown-linux-musl

    - name: Package Executable
      run: |
        cp target/release/sonomar ./sonomar
        tar czvf sonomar.tar.gz ./sonomar

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./sonomar.tar.gz
        asset_name: sonomar.tar.gz
        asset_content_type: application/gzip
